import streamlit as st
import pandas as pd
# ============================================================
# STREAMLIT SESSION STATE
# ============================================================

SESSION_DEFAULTS = {
    "analysis_completed": False,
    "evaluation": None,
    "results_df": None,
    "ragas_results": None,
    "security_results": None,
    "security_summary": None,
    "reliability_results": None,
    "failure_summary": None,
    "root_cause_df": None,
    "dataset_info": None,
    "detected_columns": None,
    "availability": None,
}

for key, default_value in SESSION_DEFAULTS.items():
    if key not in st.session_state:
        st.session_state[key] = default_value
from evaluation.dataset.data_loader import (
    load_dataset,
    get_dataset_info
)

from evaluation.dataset.schema_detector import (
    validate_dataset
)

from evaluation.dataset.metric_availability import (
    build_metric_availability
)

from evaluation.engine.evaluator import (
    run_evaluation
)

from evaluation.ragas.ragas_evaluator import (
    run_ragas_evaluation
)

from evaluation.security.security_evaluator import (
    evaluate_security,
    summarize_security
)

from visualization.charts import (
    create_metric_bar_chart,
    create_sample_score_chart
)

from explainability.failure_analysis import (
    analyze_failures,
    summarize_failures
)

from explainability.root_cause import (
    generate_root_cause_report
)
from evaluation.reliability.reliability_evaluator import (
    evaluate_reliability,
)
# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AITrustEval",
    page_icon="🛡️",
    layout="wide"
)


# ============================================================
# HEADER
# ============================================================

st.title("🛡️ AITrustEval")

st.markdown(
    """
    **AI/ML Trustworthiness, Reliability and Security Evaluation Platform**

    Upload an evaluation dataset to analyze AI system performance,
    identify failures, investigate possible root causes, evaluate
    security risks, and generate evaluation results.
    """
)

st.divider()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def format_sample_id(value):
    """
    Display numeric IDs as integers instead of 1.0, 2.0, etc.
    """

    try:
        numeric_value = float(value)

        if numeric_value.is_integer():
            return str(int(numeric_value))

    except Exception:
        pass

    return str(value)


def get_original_row(df, sample_id):
    """
    Retrieve the original dataset row using the sequential
    sample ID generated by the evaluation engine.
    """

    try:
        position = int(float(sample_id)) - 1

        if 0 <= position < len(df):
            return df.iloc[position]

    except Exception:
        pass

    return None


# ============================================================
# DATASET UPLOAD
# ============================================================

st.header("📂 Upload Evaluation Dataset")

if "uploaded_file_name" not in st.session_state:
    st.session_state.uploaded_file_name = None

uploaded_file = st.file_uploader(
    "Upload CSV, Excel or JSON dataset",
    type=["csv", "xlsx", "xls", "json"]
)

if uploaded_file is not None:
    st.session_state.uploaded_file_name = uploaded_file.name


if (
    uploaded_file is None
    and not st.session_state.analysis_completed
):

    st.info(
        "👆 Upload an evaluation dataset to begin."
    )

    st.divider()

    st.caption(
        "AITrustEval — Offline AI/ML Trustworthiness Evaluation Platform"
    )

    st.stop()

# ============================================================
# SAVE UPLOADED DATASET
# ============================================================

file_extension = (
    uploaded_file.name
    .split(".")[-1]
    .lower()
)

input_path = (
    f"data/input/uploaded_dataset.{file_extension}"
)


try:

    with open(input_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

except Exception as e:

    st.error(
        f"Unable to save uploaded dataset: {e}"
    )

    st.stop()


# ============================================================
# LOAD DATASET
# ============================================================

try:

    df = load_dataset(
        input_path
    )

except Exception as e:

    st.error(
        f"Unable to load dataset: {e}"
    )

    st.stop()


# ============================================================
# DATASET INFORMATION
# ============================================================

st.divider()

st.header("📊 Dataset Information")


dataset_info = get_dataset_info(df)


col1, col2, col3, col4 = st.columns(4)


with col1:
    st.metric(
        "Rows",
        dataset_info["rows"]
    )


with col2:
    st.metric(
        "Columns",
        dataset_info["columns"]
    )


with col3:
    st.metric(
        "Missing Values",
        dataset_info["missing_values"]
    )


with col4:
    st.metric(
        "Duplicate Rows",
        dataset_info["duplicate_rows"]
    )


# ============================================================
# DATASET PREVIEW
# ============================================================

st.subheader("Dataset Preview")

st.dataframe(
    df.head(10),
    use_container_width=True
)


# ============================================================
# SCHEMA DETECTION
# ============================================================

st.divider()

st.header("🔍 Dataset Schema Detection")


validation_result = validate_dataset(df)


detected_columns = validation_result.get(
    "detected_columns",
    {}
)


if detected_columns:

    st.subheader(
        "Detected Column Mapping"
    )

    mapping_data = []

    for field, column in detected_columns.items():

        mapping_data.append(
            {
                "AITrustEval Field": field,
                "Dataset Column": column
            }
        )

    mapping_df = pd.DataFrame(
        mapping_data
    )

    st.dataframe(
        mapping_df,
        use_container_width=True,
        hide_index=True
    )

else:

    st.warning(
        "No compatible columns were automatically detected."
    )


# ============================================================
# COLUMN VARIABLES
# ============================================================

question_column = detected_columns.get(
    "question"
)

answer_column = detected_columns.get(
    "answer"
)

ground_truth_column = detected_columns.get(
    "ground_truth"
)

context_column = detected_columns.get(
    "context"
)

latency_column = detected_columns.get(
    "latency"
)


# ============================================================
# METRIC AVAILABILITY
# ============================================================

st.divider()

st.header("📋 Metric Availability")


availability = build_metric_availability(
    validation_result
)


# ============================================================
# BASELINE METRICS
# ============================================================

st.subheader(
    "Baseline Metrics"
)

st.caption(
    "These metrics use the current lightweight baseline "
    "evaluation implementation."
)


baseline_status = {
    "Answer Relevancy": (
        question_column is not None
        and answer_column is not None
    ),

    "Answer Correctness": (
        answer_column is not None
        and ground_truth_column is not None
    ),

    "Context-Answer Similarity": (
        answer_column is not None
        and context_column is not None
    )
}


for metric, available in baseline_status.items():

    if available:

        st.success(
            f"✅ {metric} — Available"
        )

    else:

        st.warning(
            f"⚠️ {metric} — Not Available"
        )


# ============================================================
# RAGAS / LLM METRICS
# ============================================================

st.subheader(
    "Ragas / LLM Metrics"
)

st.caption(
    "These metrics require the required dataset fields and "
    "the approved local LLM environment."
)


ragas_input_ready = all(
    [
        question_column is not None,
        answer_column is not None,
        ground_truth_column is not None,
        context_column is not None
    ]
)


ragas_metrics = [
    "Faithfulness",
    "Answer Relevancy",
    "Answer Correctness",
    "Context Precision",
    "Context Recall"
]


for metric in ragas_metrics:

    if ragas_input_ready:

        st.info(
            f"🧠 {metric} — "
            "Input fields available; local Mistral/Ollama required"
        )

    else:

        st.warning(
            f"⚠️ {metric} — Required input fields unavailable"
        )


# ============================================================
# RETRIEVAL METRICS
# ============================================================

st.subheader(
    "Retrieval Metrics"
)


retrieval_metrics = [
    "Precision@K",
    "Recall@K",
    "MRR",
    "NDCG",
    "Hit Rate"
]


for metric in retrieval_metrics:

    key = (
        metric.lower()
        .replace("@", "_at_")
        .replace(" ", "_")
    )

    status = availability.get(
        key,
        False
    )

    if status:

        st.success(
            f"✅ {metric} — Available"
        )

    else:

        st.warning(
            f"⚠️ {metric} — Not Available"
        )


# ============================================================
# PERFORMANCE
# ============================================================

st.subheader(
    "Performance"
)


if latency_column:

    st.success(
        f"✅ Latency — Available "
        f"({latency_column})"
    )

else:

    st.warning(
        "⚠️ Latency — Not Available"
    )


# ============================================================
# WARNINGS
# ============================================================

warnings = validation_result.get(
    "warnings",
    []
)


if warnings:

    st.subheader(
        "⚠️ Dataset Warnings"
    )

    for warning in warnings:

        st.warning(
            warning
        )


# ============================================================
# ANALYZE BUTTON
# ============================================================

st.divider()

analyze_button = st.button(
    "🚀 Analyze Dataset",
    type="primary",
    use_container_width=True
)


# Continue if Analyze was clicked OR
# analysis was already completed earlier.
if not analyze_button and not st.session_state.analysis_completed:
    st.stop()

# ============================================================
# BASELINE EVALUATION
# ============================================================

with st.spinner(
    "Running baseline evaluation..."
):

    try:

        evaluation = run_evaluation(
            df
        )

    except Exception as e:

        st.error(
            f"Baseline evaluation failed: {e}"
        )

        st.stop()


st.success(
    "Baseline evaluation completed."
)


results_df = evaluation.get(
    "sample_results",
    pd.DataFrame()
)


# ============================================================
# SAVE BASELINE RESULTS TO SESSION STATE
# ============================================================

st.session_state.evaluation = evaluation

st.session_state.results_df = results_df

st.session_state.analysis_completed = True


# ============================================================
# BASELINE RESULTS
# ============================================================

if not results_df.empty:

    st.divider()

    st.header(
        "📈 Baseline Evaluation Results"
    )


    metric_columns = [
        "answer_relevancy",
        "answer_correctness",
        "context_answer_similarity"
    ]


    available_metric_columns = [
        metric
        for metric in metric_columns
        if metric in results_df.columns
    ]


    averages = {}


    for metric in available_metric_columns:

        averages[metric] = (
            pd.to_numeric(
                results_df[metric],
                errors="coerce"
            )
            .mean()
        )


    # ========================================================
    # KPI CARDS
    # ========================================================

    if averages:

        kpi_columns = st.columns(
            len(averages)
        )


        for index, (
            metric,
            value
        ) in enumerate(
            averages.items()
        ):

            with kpi_columns[index]:

                st.metric(
                    metric.replace(
                        "_",
                        " "
                    ).title(),
                    f"{value:.3f}"
                )


    # ========================================================
    # BASELINE CHART
    # ========================================================

    if averages:

        st.subheader(
            "Average Evaluation Scores"
        )


        fig = create_metric_bar_chart(
            averages
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    # ========================================================
    # SAMPLE SCORE CHART
    # ========================================================

    st.subheader(
        "Evaluation Scores by Sample"
    )


    try:

        fig = create_sample_score_chart(
            results_df
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    except Exception as e:

        st.warning(
            f"Unable to generate sample score chart: {e}"
        )


    # ========================================================
    # RESULTS TABLE
    # ========================================================

    st.subheader(
        "Sample-Level Baseline Results"
    )


    st.dataframe(
        results_df,
        use_container_width=True
    )


    # ========================================================
    # DOWNLOAD
    # ========================================================

    csv_data = (
        results_df
        .to_csv(index=False)
        .encode("utf-8")
    )


    st.download_button(
        label="⬇️ Download Baseline Results",
        data=csv_data,
        file_name="baseline_evaluation_results.csv",
        mime="text/csv"
    )


# ============================================================
# RAGAS + MISTRAL
# ============================================================

st.divider()

st.header(
    "🧠 Ragas LLM Evaluation"
)

st.markdown(
    """
    Ragas provides LLM-based evaluation of answer and RAG
    quality. In the DRDO environment, the evaluator is
    intended to use the approved local **Mistral model
    through Ollama**.
    """
)


with st.spinner(
    "Checking local Ragas environment..."
):

    try:

        ragas_evaluation = run_ragas_evaluation(
            df
        )

    except Exception as e:

        ragas_evaluation = {
            "status": "error",
            "message": str(e)
        }


# ============================================================
# SAVE RAGAS RESULT TO SESSION STATE
# ============================================================

st.session_state.ragas_results = (
    ragas_evaluation.get(
        "results",
        pd.DataFrame()
    )
)


ragas_status = ragas_evaluation.get(
    "status"
)


if ragas_status == "unavailable":

    st.warning(
        "⚠️ Ragas + Ollama/Mistral is currently unavailable."
    )

    st.info(
        """
        This is expected on the current Windows
        development machine because Ollama is not
        installed.

        The same application can use the approved
        local Ollama + Mistral environment in DRDO.
        """
    )


elif ragas_status == "error":

    st.error(
        "Ragas evaluation could not be completed."
    )

    st.error(
        ragas_evaluation.get(
            "message",
            "Unknown error."
        )
    )


elif ragas_status == "success":

    st.success(
        "✅ Ragas evaluation completed successfully."
    )


    st.write(
        f"**Evaluation Model:** "
        f"{ragas_evaluation.get('model', 'mistral')}"
    )


    ragas_mapping = ragas_evaluation.get(
        "mapping",
        {}
    )


    if ragas_mapping:

        st.subheader(
            "Ragas Column Mapping"
        )


        ragas_mapping_df = pd.DataFrame(
            [
                {
                    "Ragas Field": field,
                    "Dataset Column": column
                }

                for field, column
                in ragas_mapping.items()
            ]
        )


        st.dataframe(
            ragas_mapping_df,
            use_container_width=True,
            hide_index=True
        )


    ragas_results = ragas_evaluation.get(
        "results",
        pd.DataFrame()
    )


    # Keep the latest Ragas results in session state
    st.session_state.ragas_results = ragas_results


    if not ragas_results.empty:

        st.subheader(
            "Ragas Metric Results"
        )


        st.dataframe(
            ragas_results,
            use_container_width=True
        )


        ragas_metric_names = [
            "faithfulness",
            "answer_relevancy",
            "answer_correctness",
            "context_precision",
            "context_recall"
        ]


        ragas_averages = {}


        for metric in ragas_metric_names:

            if metric in ragas_results.columns:

                numeric_values = pd.to_numeric(
                    ragas_results[metric],
                    errors="coerce"
                )


                if numeric_values.notna().any():

                    ragas_averages[metric] = (
                        numeric_values.mean()
                    )


        if ragas_averages:

            st.subheader(
                "Average Ragas Scores"
            )


            ragas_kpis = st.columns(
                len(ragas_averages)
            )


            for index, (
                metric,
                value
            ) in enumerate(
                ragas_averages.items()
            ):

                with ragas_kpis[index]:

                    st.metric(
                        metric.replace(
                            "_",
                            " "
                        ).title(),
                        f"{value:.3f}"
                    )


            ragas_chart = (
                create_metric_bar_chart(
                    ragas_averages
                )
            )


            st.plotly_chart(
                ragas_chart,
                use_container_width=True
            )


            ragas_csv = (
                ragas_results
                .to_csv(index=False)
                .encode("utf-8")
            )


            st.download_button(
                label="⬇️ Download Ragas Results",
                data=ragas_csv,
                file_name="ragas_evaluation_results.csv",
                mime="text/csv"
            )


# ============================================================
# FAILURE INVESTIGATION
# ============================================================

if not results_df.empty:

    st.divider()

    st.header(
        "🔎 Failure Investigation"
    )


    st.markdown(
        """
        This section identifies samples with low baseline
        evaluation scores and provides a preliminary
        root-cause investigation.

        **Note:** Current thresholds are preliminary
        investigation thresholds and are not official
        pass/fail standards.
        """
    )


    try:

        failures_df = analyze_failures(
            results_df
        )

        failure_summary = summarize_failures(
            failures_df
        )

        root_cause_df = generate_root_cause_report(
            failures_df
        )
        st.session_state.failure_summary = failure_summary
        st.session_state.root_cause_df = root_cause_df

    except Exception as e:

        st.error(
            f"Failure analysis failed: {e}"
        )

        root_cause_df = pd.DataFrame()


    if not root_cause_df.empty:

        st.subheader(
            "Failure Summary"
        )


        col1, col2, col3, col4 = st.columns(4)


        with col1:

            st.metric(
                "Total Failures",
                failure_summary.get(
                    "total_failures",
                    0
                )
            )


        with col2:

            st.metric(
                "High Severity",
                failure_summary.get(
                    "high",
                    0
                )
            )


        with col3:

            st.metric(
                "Medium Severity",
                failure_summary.get(
                    "medium",
                    0
                )
            )


        with col4:

            st.metric(
                "Low Severity",
                failure_summary.get(
                    "low",
                    0
                )
            )


        st.subheader(
            "Failed Samples"
        )


        display_columns = [
            "id",
            "severity",
            "failed_metrics"
        ]


        available_columns = [
            column
            for column in display_columns
            if column in root_cause_df.columns
        ]


        st.dataframe(
            root_cause_df[
                available_columns
            ],
            use_container_width=True,
            hide_index=True
        )


        st.subheader(
            "🧪 Sample-Level Investigation"
        )


        failure_ids = (
            root_cause_df["id"]
            .tolist()
        )


        selected_id = st.selectbox(
            "Select a failed sample",
            failure_ids,
            format_func=format_sample_id,
            key="failure_sample"
        )


        selected_failure = root_cause_df[
            root_cause_df["id"] == selected_id
        ].iloc[0]


        selected_results = results_df[
            results_df["id"] == selected_id
        ]


        if not selected_results.empty:

            selected_result = (
                selected_results.iloc[0]
            )


            st.markdown(
                "### 📊 Evaluation Scores"
            )


            score_columns = [
                "answer_relevancy",
                "answer_correctness",
                "context_answer_similarity"
            ]


            available_scores = [
                metric
                for metric in score_columns
                if metric in selected_result.index
            ]


            if available_scores:

                score_cols = st.columns(
                    len(available_scores)
                )


                for index, metric in enumerate(
                    available_scores
                ):

                    with score_cols[index]:

                        st.metric(
                            metric.replace(
                                "_",
                                " "
                            ).title(),
                            f"{float(selected_result[metric]):.3f}"
                        )


            severity = selected_failure.get(
                "severity",
                "Unknown"
            )


            st.markdown(
                "### 🚨 Severity"
            )


            if severity == "High":

                st.error(
                    f"High Severity — Sample "
                    f"{format_sample_id(selected_id)}"
                )

            elif severity == "Medium":

                st.warning(
                    f"Medium Severity — Sample "
                    f"{format_sample_id(selected_id)}"
                )

            else:

                st.info(
                    f"Low Severity — Sample "
                    f"{format_sample_id(selected_id)}"
                )


            st.markdown(
                "### ❌ Failed Metrics"
            )


            st.write(
                selected_failure.get(
                    "failed_metrics",
                    "Not available"
                )
            )


            st.markdown(
                "### 🔍 Preliminary Root Cause"
            )


            st.warning(
                selected_failure.get(
                    "root_cause",
                    "Root cause not available."
                )
            )


            st.markdown(
                "### 💡 Recommendation"
            )


            st.info(
                selected_failure.get(
                    "recommendation",
                    "No recommendation available."
                )
            )


            original_row = get_original_row(
                df,
                selected_id
            )


            if original_row is not None:

                st.markdown(
                    "### 📚 Evidence"
                )


                with st.expander(
                    "❓ View Question"
                ):

                    if question_column:

                        st.write(
                            original_row.get(
                                question_column,
                                "Not available"
                            )
                        )

                    else:

                        st.write(
                            "Not available"
                        )


                with st.expander(
                    "🤖 View Generated Answer"
                ):

                    if answer_column:

                        st.write(
                            original_row.get(
                                answer_column,
                                "Not available"
                            )
                        )

                    else:

                        st.write(
                            "Not available"
                        )


                with st.expander(
                    "🎯 View Ground Truth"
                ):

                    if ground_truth_column:

                        st.write(
                            original_row.get(
                                ground_truth_column,
                                "Not available"
                            )
                        )

                    else:

                        st.write(
                            "Not available"
                        )


                with st.expander(
                    "📄 View Retrieved Context"
                ):

                    if context_column:

                        st.write(
                            original_row.get(
                                context_column,
                                "Not available"
                            )
                        )

                    else:

                        st.write(
                            "Not available"
                        )


# ============================================================
# SECURITY EVALUATION
# ============================================================

st.divider()

st.header(
    "🛡️ Security Evaluation"
)


st.markdown(
    """
    AITrustEval performs two levels of security evaluation:

    **1. Rule-Based Security Screening**
    - Prompt Injection
    - Jailbreak
    - Toxicity
    - Data Leakage

    **2. Local Mistral Semantic Evaluation**
    - Semantic interpretation of potential attacks
    - Security reasoning
    - Evidence
    - Recommendations

    The final result combines both evaluations when
    Mistral is available.
    """
)


if (
    question_column
    and answer_column
):

    try:

        with st.spinner(
            "Running security evaluation..."
        ):

            security_results = evaluate_security(
                df,
                question_column=question_column,
                answer_column=answer_column,
                use_mistral=True,
                model="mistral"
            )


        security_summary = summarize_security(
            security_results
        )
        st.session_state.security_results = security_results
        st.session_state.security_summary = security_summary


        # ====================================================
        # MISTRAL STATUS
        # ====================================================

        if "mistral_status" in security_results.columns:

            mistral_statuses = (
                security_results[
                    "mistral_status"
                ]
                .astype(str)
                .str.lower()
                .unique()
            )


            if "success" in mistral_statuses:

                st.success(
                    "🧠 Local Mistral semantic security "
                    "evaluation is active."
                )

            elif "unavailable" in mistral_statuses:

                st.warning(
                    "⚠️ Local Mistral semantic evaluation "
                    "is unavailable. Combined results are "
                    "currently based on rule-based screening."
                )

                st.info(
                    """
                    This is expected on the current Windows
                    development machine if Ollama/Mistral is
                    not installed.

                    In the DRDO environment, the local Mistral
                    evaluator can provide semantic security
                    analysis.
                    """
                )

            else:

                st.warning(
                    "⚠️ Mistral semantic evaluation "
                    "was not completed."
                )


        # ====================================================
        # SECURITY SUMMARY
        # ====================================================

        st.subheader(
            "Security Summary"
        )


        col1, col2, col3, col4 = st.columns(4)


        with col1:

            st.metric(
                "Total Samples",
                security_summary[
                    "total_samples"
                ]
            )


        with col2:

            st.metric(
                "High Risk",
                security_summary[
                    "high_risk"
                ]
            )


        with col3:

            st.metric(
                "Medium Risk",
                security_summary[
                    "medium_risk"
                ]
            )


        with col4:

            st.metric(
                "Low Risk",
                security_summary[
                    "low_risk"
                ]
            )


        # ====================================================
        # SECURITY CHECK RESULTS
        # ====================================================

        st.subheader(
            "Security Check Results"
        )


        col1, col2, col3, col4 = st.columns(4)


        security_counts = [
            (
                "Prompt Injection",
                "prompt_injection"
            ),
            (
                "Jailbreak",
                "jailbreak"
            ),
            (
                "Toxicity",
                "toxicity"
            ),
            (
                "Data Leakage",
                "data_leakage"
            )
        ]


        for column, (
            label,
            category
        ) in zip(
            [col1, col2, col3, col4],
            security_counts
        ):

            with column:

                st.metric(
                    label,
                    security_summary[
                        category
                    ]
                )


        # ====================================================
        # RULE VS MISTRAL VS COMBINED
        # ====================================================

        st.subheader(
            "Rule-Based vs Mistral vs Combined"
        )


        comparison_rows = []


        for category, label in security_counts:

            rule_risk_column = (
                f"{category}_risk"
            )

            mistral_risk_column = (
                f"{category}_mistral_risk"
            )

            combined_risk_column = (
                f"{category}_combined_risk"
            )


            comparison_rows.append(
                {
                    "Security Category": label,

                    "Rule-Based Risk": (
                        security_results[
                            rule_risk_column
                        ]
                        .replace(
                            "",
                            "Low"
                        )
                        .mode()
                        .iloc[0]
                        if rule_risk_column
                        in security_results.columns
                        else "N/A"
                    ),

                    "Mistral Risk": (
                        security_results[
                            mistral_risk_column
                        ]
                        .mode()
                        .iloc[0]
                        if mistral_risk_column
                        in security_results.columns
                        else "N/A"
                    ),

                    "Combined Risk": (
                        security_results[
                            combined_risk_column
                        ]
                        .mode()
                        .iloc[0]
                        if combined_risk_column
                        in security_results.columns
                        else "N/A"
                    )
                }
            )


        comparison_df = pd.DataFrame(
            comparison_rows
        )


        st.dataframe(
            comparison_df,
            use_container_width=True,
            hide_index=True
        )


        # ====================================================
        # FULL SECURITY RESULTS
        # ====================================================

        st.subheader(
            "Sample-Level Security Results"
        )


        summary_columns = [
            "id",

            "prompt_injection",
            "prompt_injection_risk",
            "prompt_injection_mistral_risk",
            "prompt_injection_combined_risk",

            "jailbreak",
            "jailbreak_risk",
            "jailbreak_mistral_risk",
            "jailbreak_combined_risk",

            "toxicity",
            "toxicity_risk",
            "toxicity_mistral_risk",
            "toxicity_combined_risk",

            "data_leakage",
            "data_leakage_risk",
            "data_leakage_mistral_risk",
            "data_leakage_combined_risk",

            "overall_security_risk",
            "mistral_status"
        ]


        available_security_columns = [
            column
            for column in summary_columns
            if column in security_results.columns
        ]


        st.dataframe(
            security_results[
                available_security_columns
            ],
            use_container_width=True,
            hide_index=True
        )


        # ====================================================
        # DOWNLOAD SECURITY RESULTS
        # ====================================================

        security_csv = (
            security_results
            .to_csv(index=False)
            .encode("utf-8")
        )


        st.download_button(
            label="⬇️ Download Combined Security Results",
            data=security_csv,
            file_name="combined_security_evaluation_results.csv",
            mime="text/csv"
        )


        # ====================================================
        # SECURITY SAMPLE INVESTIGATION
        # ====================================================

        st.subheader(
            "🔐 Security Sample Investigation"
        )


        security_ids = (
            security_results[
                "id"
            ].tolist()
        )


        selected_security_id = st.selectbox(
            "Select a sample for security investigation",
            security_ids,
            format_func=format_sample_id,
            key="security_sample"
        )


        security_row = security_results[
            security_results["id"]
            == selected_security_id
        ].iloc[0]


        # ====================================================
        # OVERALL RISK
        # ====================================================

        overall_risk = security_row[
            "overall_security_risk"
        ]


        if overall_risk == "High":

            st.error(
                f"🔴 Overall Security Risk: {overall_risk}"
            )

        elif overall_risk == "Medium":

            st.warning(
                f"🟠 Overall Security Risk: {overall_risk}"
            )

        else:

            st.success(
                f"🟢 Overall Security Risk: {overall_risk}"
            )


        # ====================================================
        # MISTRAL STATUS FOR SELECTED SAMPLE
        # ====================================================

        selected_mistral_status = (
            security_row.get(
                "mistral_status",
                "unknown"
            )
        )


        if selected_mistral_status == "success":

            st.success(
                "🧠 Mistral semantic evaluation: Available"
            )

        elif selected_mistral_status == "unavailable":

            st.warning(
                "🧠 Mistral semantic evaluation: Unavailable"
            )


        # ====================================================
        # CATEGORY INVESTIGATION
        # ====================================================

        st.markdown(
            "### Security Checks"
        )


        for category, label in security_counts:

            rule_detected = security_row.get(
                category,
                False
            )

            rule_risk = security_row.get(
                f"{category}_risk",
                "Low"
            )

            mistral_detected = security_row.get(
                f"{category}_mistral_detected",
                False
            )

            mistral_risk = security_row.get(
                f"{category}_mistral_risk",
                "Unavailable"
            )

            combined_risk = security_row.get(
                f"{category}_combined_risk",
                rule_risk
            )


            with st.expander(
                f"🔎 {label}"
            ):

                col1, col2, col3 = st.columns(3)


                with col1:

                    st.markdown(
                        "**Rule-Based**"
                    )

                    if rule_detected:

                        st.error(
                            f"Detected — {rule_risk}"
                        )

                    else:

                        st.success(
                            f"No indicator — {rule_risk}"
                        )


                with col2:

                    st.markdown(
                        "**Mistral**"
                    )

                    if mistral_risk == "Unavailable":

                        st.warning(
                            "Unavailable"
                        )

                    elif mistral_detected:

                        st.error(
                            f"Detected — {mistral_risk}"
                        )

                    else:

                        st.success(
                            f"No indicator — {mistral_risk}"
                        )


                with col3:

                    st.markdown(
                        "**Combined**"
                    )


                    if combined_risk == "High":

                        st.error(
                            f"High Risk"
                        )

                    elif combined_risk == "Medium":

                        st.warning(
                            f"Medium Risk"
                        )

                    else:

                        st.success(
                            f"Low Risk"
                        )


                reason = security_row.get(
                    f"{category}_reason",
                    ""
                )

                evidence = security_row.get(
                    f"{category}_evidence",
                    ""
                )

                recommendation = security_row.get(
                    f"{category}_recommendation",
                    ""
                )


                if reason:

                    st.markdown(
                        "**Reason**"
                    )

                    st.write(
                        reason
                    )


                if evidence:

                    st.markdown(
                        "**Evidence**"
                    )

                    st.write(
                        evidence
                    )


                if recommendation:

                    st.markdown(
                        "**Recommendation**"
                    )

                    st.info(
                        recommendation
                    )


        # ====================================================
        # ORIGINAL SECURITY EVIDENCE
        # ====================================================

        st.markdown(
            "### 📚 Security Evidence"
        )


        original_security_row = get_original_row(
            df,
            selected_security_id
        )


        if original_security_row is not None:

            with st.expander(
                "❓ View User Query"
            ):

                st.write(
                    original_security_row.get(
                        question_column,
                        "Not available"
                    )
                )


            with st.expander(
                "🤖 View Model Response"
            ):

                st.write(
                    original_security_row.get(
                        answer_column,
                        "Not available"
                    )
                )


            if context_column:

                with st.expander(
                    "📄 View Retrieved Context"
                ):

                    st.write(
                        original_security_row.get(
                            context_column,
                            "Not available"
                        )
                    )


            if ground_truth_column:

                with st.expander(
                    "🎯 View Ground Truth"
                ):

                    st.write(
                        original_security_row.get(
                            ground_truth_column,
                            "Not available"
                        )
                    )


    except Exception as e:

        st.error(
            f"Security evaluation failed: {e}"
        )

else:

    st.warning(
        """
        Security evaluation requires both a
        question/query column and an answer/response column.
        """
    )



# ============================================================
# RELIABILITY & PERFORMANCE EVALUATION
# ============================================================

st.divider()

st.header(
    "⚡ Reliability & Performance Evaluation"
)

st.markdown(
    """
AITrustEval evaluates reliability and performance only when the
uploaded dataset contains the information required for each metric.

Metrics that cannot be calculated from the uploaded dataset are
reported as **Not Available** with the reason. No performance
values are fabricated.
"""
)

try:

    with st.spinner(
        "Running reliability and performance evaluation..."
    ):

        reliability_results = evaluate_reliability(
            df
        )
        st.session_state.reliability_results = reliability_results

    # ========================================================
    # METRIC AVAILABILITY
    # ========================================================

    st.subheader(
        "📊 Reliability Metric Availability"
    )

    available_reliability_metrics = (
        reliability_results.get(
            "available_metrics",
            []
        )
    )

    unavailable_reliability_metrics = (
        reliability_results.get(
            "unavailable_metrics",
            []
        )
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Total Samples",
            reliability_results.get(
                "total_samples",
                len(df)
            )
        )

    with col2:

        st.metric(
            "Available Metrics",
            len(
                available_reliability_metrics
            )
        )

    with col3:

        st.metric(
            "Unavailable Metrics",
            len(
                unavailable_reliability_metrics
            )
        )

    if available_reliability_metrics:

        st.success(
            "✅ Available: "
            + ", ".join(
                available_reliability_metrics
            )
        )

    if unavailable_reliability_metrics:

        st.warning(
            "Some reliability metrics cannot be calculated "
            "from this dataset."
        )

        unavailable_reliability_df = pd.DataFrame(
            unavailable_reliability_metrics
        )

        if not unavailable_reliability_df.empty:

            unavailable_reliability_df = (
                unavailable_reliability_df.rename(
                    columns={
                        "metric": "Metric",
                        "reason": "Reason"
                    }
                )
            )

            st.dataframe(
                unavailable_reliability_df[
                    [
                        "Metric",
                        "Reason"
                    ]
                ],
                use_container_width=True,
                hide_index=True
            )

    # ========================================================
    # LATENCY
    # ========================================================

    st.subheader(
        "⏱️ Latency"
    )

    latency_result = reliability_results.get(
        "latency",
        {}
    )

    if latency_result.get(
        "available",
        False
    ):

        latency_col1, latency_col2, latency_col3, latency_col4 = (
            st.columns(4)
        )

        with latency_col1:

            st.metric(
                "Mean",
                f"{latency_result['mean']:.2f} ms"
            )

        with latency_col2:

            st.metric(
                "Median",
                f"{latency_result['median']:.2f} ms"
            )

        with latency_col3:

            st.metric(
                "P95",
                f"{latency_result['p95']:.2f} ms"
            )

        with latency_col4:

            st.metric(
                "P99",
                f"{latency_result['p99']:.2f} ms"
            )

        st.caption(
            f"Source column: "
            f"`{latency_result.get('column', 'Unknown')}`"
        )

        latency_details = pd.DataFrame(
            {
                "Statistic": [
                    "Minimum",
                    "Mean",
                    "Median",
                    "Maximum",
                    "P95",
                    "P99"
                ],
                "Latency (ms)": [
                    latency_result["min"],
                    latency_result["mean"],
                    latency_result["median"],
                    latency_result["max"],
                    latency_result["p95"],
                    latency_result["p99"]
                ]
            }
        )

        with st.expander(
            "View latency statistics"
        ):

            st.dataframe(
                latency_details,
                use_container_width=True,
                hide_index=True
            )

    else:

        st.info(
            "ℹ️ Latency — Not Available\n\n"
            + latency_result.get(
                "reason",
                "No valid latency information was found."
            )
        )

    # ========================================================
    # SUCCESS / FAILURE
    # ========================================================

    st.subheader(
        "✅ Success / Failure"
    )

    success_failure_result = (
        reliability_results.get(
            "success_failure",
            {}
        )
    )

    if success_failure_result.get(
        "available",
        False
    ):

        sf_col1, sf_col2, sf_col3, sf_col4 = (
            st.columns(4)
        )

        with sf_col1:

            st.metric(
                "Success Rate",
                f"{success_failure_result['success_rate']:.2%}"
            )

        with sf_col2:

            st.metric(
                "Failure Rate",
                f"{success_failure_result['failure_rate']:.2%}"
            )

        with sf_col3:

            st.metric(
                "Successful Samples",
                success_failure_result[
                    "success_count"
                ]
            )

        with sf_col4:

            st.metric(
                "Failed Samples",
                success_failure_result[
                    "failure_count"
                ]
            )

        st.caption(
            f"Source column: "
            f"`{success_failure_result.get('column', 'Unknown')}`"
        )

    else:

        st.info(
            "ℹ️ Success / Failure — Not Available\n\n"
            + success_failure_result.get(
                "reason",
                "No usable status information was found."
            )
        )

    # ========================================================
    # RESPONSE CONSISTENCY
    # ========================================================

    st.subheader(
        "🔄 Response Consistency"
    )

    consistency_result = (
        reliability_results.get(
            "consistency",
            {}
        )
    )

    if consistency_result.get(
        "available",
        False
    ):

        consistency_col1, consistency_col2 = (
            st.columns(2)
        )

        with consistency_col1:

            st.metric(
                "Consistency Score",
                f"{consistency_result['consistency_score']:.4f}"
            )

        with consistency_col2:

            st.metric(
                "Repeated Question Groups",
                consistency_result[
                    "repeated_question_groups"
                ]
            )

        st.caption(
            consistency_result.get(
                "method",
                "Consistency methodology not specified."
            )
        )

        consistency_groups = (
            consistency_result.get(
                "groups",
                []
            )
        )

        if consistency_groups:

            with st.expander(
                "View consistency by repeated question"
            ):

                consistency_df = pd.DataFrame(
                    consistency_groups
                )

                st.dataframe(
                    consistency_df,
                    use_container_width=True,
                    hide_index=True
                )

    else:

        st.info(
            "ℹ️ Response Consistency — Not Available\n\n"
            + consistency_result.get(
                "reason",
                "Consistency could not be calculated."
            )
        )

    # ========================================================
    # ROBUSTNESS
    # ========================================================

    st.subheader(
        "🧪 Robustness"
    )

    robustness_result = (
        reliability_results.get(
            "robustness",
            {}
        )
    )

    if robustness_result.get(
        "available",
        False
    ):

        st.success(
            "✅ Robustness input data is available."
        )

        st.write(
            robustness_result.get(
                "message",
                "Variation data is available."
            )
        )

        if robustness_result.get(
            "column"
        ):

            st.caption(
                f"Variation column: "
                f"`{robustness_result['column']}`"
            )

        st.info(
            "A final robustness score requires a defined "
            "original-to-variant evaluation methodology. "
            "AITrustEval does not invent a robustness score."
        )

    else:

        st.info(
            "ℹ️ Robustness — Not Available\n\n"
            + robustness_result.get(
                "reason",
                "No robustness evaluation data was detected."
            )
        )

    # ========================================================
    # RELIABILITY SUMMARY DOWNLOAD
    # ========================================================

    st.subheader(
        "📥 Reliability Summary"
    )

    reliability_download_rows = []

    for metric_name in [
        "latency",
        "success_failure",
        "consistency",
        "robustness"
    ]:

        metric_result = reliability_results.get(
            metric_name,
            {}
        )

        reliability_download_rows.append(
            {
                "Metric": metric_name,
                "Available": metric_result.get(
                    "available",
                    False
                ),
                "Reason": metric_result.get(
                    "reason",
                    ""
                )
            }
        )

    reliability_summary_df = pd.DataFrame(
        reliability_download_rows
    )

    st.download_button(
        label="⬇️ Download Reliability Summary",
        data=reliability_summary_df.to_csv(
            index=False
        ).encode("utf-8"),
        file_name="reliability_summary.csv",
        mime="text/csv"
    )

except Exception as e:

    st.error(
        f"Reliability evaluation failed: {e}"
    )

    with st.expander(
        "View reliability error details"
    ):

        st.exception(e)


# ============================================================
# CURRENT LIMITATIONS
# ============================================================

st.divider()

st.header(
    "⚠️ Current Evaluation Limitations"
)

st.markdown(
    """
    - Baseline answer-quality scores currently use
      TF-IDF similarity.
    - Ragas LLM-based evaluation requires the approved
      local Ollama + Mistral environment.
    - Retrieval metrics such as Precision@K, Recall@K,
      MRR, NDCG and Hit Rate require ranked retrieval
      results and relevance information.
    - Current failure thresholds are preliminary
      investigation thresholds.
    - Rule-based security checks are preliminary
      screening mechanisms.
    - Mistral semantic security evaluation becomes
      available when the approved local Ollama + Mistral
      environment is available.
    - Combined security risk uses the highest risk detected
      across the rule-based and Mistral evaluations.
    """
)


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "AITrustEval — Offline AI/ML Trustworthiness Evaluation Platform"
)
# ============================================================
# REPORT GENERATION
# ============================================================

st.divider()

st.header("📄 Evaluation Report Generation")

st.markdown(
    """
    Generate a professional AITrustEval evaluation report from the
    results of the current dataset analysis.

    The report can include:

    - Dataset information
    - Detected schema
    - Metric availability
    - Baseline evaluation
    - RAGAS / LLM evaluation
    - Security evaluation
    - Reliability and performance
    - Failure analysis
    - Root-cause analysis
    - Recommendations

    Metrics that cannot be calculated from the uploaded dataset
    are reported as unavailable instead of being fabricated.
    """
)


# ============================================================
# CHECK WHETHER ANALYSIS WAS COMPLETED
# ============================================================

if "evaluation" not in locals():

    st.info(
        "Run the dataset analysis first. "
        "The report will be generated from the current analysis results."
    )

else:

    try:

        # ----------------------------------------------------
        # Import report functions
        # ----------------------------------------------------

        from outputs.reports.report_generator import (
            build_report_data,
            generate_html_report,
            generate_pdf_report
        )


        # ====================================================
        # BASELINE METRICS
        # ====================================================

        report_baseline_metrics = {}

        if (
            "results_df" in locals()
            and isinstance(results_df, pd.DataFrame)
            and not results_df.empty
        ):

            baseline_metrics = [
                "answer_relevancy",
                "answer_correctness",
                "context_answer_similarity"
            ]

            for metric in baseline_metrics:

                if metric in results_df.columns:

                    values = pd.to_numeric(
                        results_df[metric],
                        errors="coerce"
                    )

                    if values.notna().any():

                        report_baseline_metrics[metric] = float(
                            values.mean()
                        )


        # ====================================================
        # RAGAS RESULTS
        # ====================================================

        report_ragas_result = {}

        if (
            "ragas_results" in locals()
            and isinstance(ragas_results, pd.DataFrame)
            and not ragas_results.empty
        ):

            ragas_metrics = {}

            for metric in [
                "faithfulness",
                "answer_relevancy",
                "answer_correctness",
                "context_precision",
                "context_recall"
            ]:

                if metric in ragas_results.columns:

                    values = pd.to_numeric(
                        ragas_results[metric],
                        errors="coerce"
                    )

                    if values.notna().any():

                        ragas_metrics[metric] = float(
                            values.mean()
                        )

            report_ragas_result = {
                "metrics": ragas_metrics
            }


        # ====================================================
        # SECURITY RESULTS
        # ====================================================

        report_security_result = {}

        if (
            "security_results" in locals()
            and isinstance(security_results, pd.DataFrame)
            and not security_results.empty
        ):

            try:

                report_security_result = {
                    "summary": summarize_security(
                        security_results
                    )
                }

            except Exception:

                report_security_result = {}


        # ====================================================
        # RELIABILITY RESULTS
        # ====================================================

        report_reliability_result = {}

        if "reliability_results" in locals():

            if isinstance(
                reliability_results,
                dict
            ):

                report_reliability_result = (
                    reliability_results
                )


        # ====================================================
        # FAILURE SUMMARY
        # ====================================================

        report_failure_summary = {}

        if "failure_summary" in locals():

            if isinstance(
                failure_summary,
                dict
            ):

                report_failure_summary = (
                    failure_summary
                )


        # ====================================================
        # ROOT CAUSE REPORT
        # ====================================================

        report_root_cause = None

        if (
            "root_cause_df" in locals()
            and isinstance(
                root_cause_df,
                pd.DataFrame
            )
            and not root_cause_df.empty
        ):

           report_root_cause = root_cause_df.to_dict(
    orient="records"
)


        # ====================================================
        # RECOMMENDATIONS
        # ====================================================

        report_recommendations = []

        if (
            "root_cause_df" in locals()
            and isinstance(
                root_cause_df,
                pd.DataFrame
            )
            and not root_cause_df.empty
            and "recommendation" in root_cause_df.columns
        ):

            recommendations = (
                root_cause_df["recommendation"]
                .dropna()
                .astype(str)
                .tolist()
            )

            # Remove duplicate recommendations
            report_recommendations = list(
                dict.fromkeys(
                    recommendations
                )
            )


        # ====================================================
        # BUILD COMPLETE REPORT DATA
        # ====================================================

        report_data = build_report_data(

            evaluation_result=evaluation,

            dataset_info=dataset_info,

            schema_mapping=detected_columns,

            metric_availability=availability,

            baseline_metrics={
                "averages": report_baseline_metrics
            },

            ragas_result=report_ragas_result,

            security_result=report_security_result,

            reliability_result=report_reliability_result,

            failure_summary=report_failure_summary,

            root_cause_report=report_root_cause,

            recommendations=report_recommendations
        )


        # ====================================================
        # REPORT BUTTONS
        # ====================================================

        st.subheader("📑 Generate Reports")

        st.caption(
            "Reports are saved automatically inside "
            "outputs/reports/"
        )


        col1, col2, col3 = st.columns(3)


        # ====================================================
        # PDF
        # ====================================================

        with col1:

            if st.button(
                "📄 Generate PDF",
                use_container_width=True
            ):

                with st.spinner(
                    "Generating PDF report..."
                ):

                    pdf_path = generate_pdf_report(
                        report_data
                    )

                st.success(
                    "PDF report generated successfully."
                )

                with open(
                    pdf_path,
                    "rb"
                ) as file:

                    st.download_button(

                        label="⬇️ Download PDF",

                        data=file.read(),

                        file_name=pdf_path.name,

                        mime="application/pdf",

                        use_container_width=True
                    )


        # ====================================================
        # HTML
        # ====================================================

        with col2:

            if st.button(
                "🌐 Generate HTML",
                use_container_width=True
            ):

                with st.spinner(
                    "Generating HTML report..."
                ):

                    html_path = generate_html_report(
                        report_data
                    )

                st.success(
                    "HTML report generated successfully."
                )

                with open(
                    html_path,
                    "rb"
                ) as file:

                    st.download_button(

                        label="⬇️ Download HTML",

                        data=file.read(),

                        file_name=html_path.name,

                        mime="text/html",

                        use_container_width=True
                    )


        # ====================================================
        # BOTH REPORTS
        # ====================================================

        with col3:

            if st.button(
                "📦 Generate Both",
                use_container_width=True
            ):

                with st.spinner(
                    "Generating PDF and HTML reports..."
                ):

                    pdf_path = generate_pdf_report(
                        report_data
                    )

                    html_path = generate_html_report(
                        report_data
                    )

                st.success(
                    "PDF and HTML reports generated successfully."
                )

                st.markdown("### Download Reports")

                download_col1, download_col2 = st.columns(2)


                # PDF DOWNLOAD
                with download_col1:

                    with open(
                        pdf_path,
                        "rb"
                    ) as file:

                        st.download_button(

                            label="⬇️ PDF",

                            data=file.read(),

                            file_name=pdf_path.name,

                            mime="application/pdf",

                            use_container_width=True
                        )


                # HTML DOWNLOAD
                with download_col2:

                    with open(
                        html_path,
                        "rb"
                    ) as file:

                        st.download_button(

                            label="⬇️ HTML",

                            data=file.read(),

                            file_name=html_path.name,

                            mime="text/html",

                            use_container_width=True
                        )


        # ====================================================
        # REPORT LOCATION
        # ====================================================

        st.info(
            """
            📁 Reports are stored in:

            `AITrustEval/outputs/reports/`

            No additional folder is required.
            """
        )


    # ========================================================
    # REPORT ERROR
    # ========================================================

    except Exception as e:

        st.error(
            f"Report generation error: {e}"
        )

        with st.expander(
            "🔍 View Technical Error"
        ):

            st.exception(e)